Project.create(name: "Vegetable Garden", description: "3 sisters - corn, pole beans, squash")
Project.create(name: "Moon Landing", description: "One small step for man, one giant leap for mankind.")
Project.create(name: "Learn karate", description: "Wax on, wax off.")
Project.create(name: "Rescue Princess", description: "It's a me, Mario")

Task.create(name: "task 1", project_id: 1, complete: true, priority: 1, due_at: "2013-1-1")
Task.create(name: "task 2", project_id: 1, complete: false, priority: 2, due_at: "2013-1-10")
Task.create(name: "task 3", project_id: 1, complete: true, priority: 3, due_at: "2013-1-20")
Task.create(name: "task 4", project_id: 1, complete: false, priority: 4, due_at: "2013-2-1")
Task.create(name: "task 5", project_id: 1, complete: true, priority: 1, due_at: "2013-2-10")
Task.create(name: "task 6", project_id: 1, complete: false, priority: 2, due_at: "2013-2-19")

Task.create(name: "task 1", project_id: 2, complete: false, priority: 3, due_at: "2013-3-11")
Task.create(name: "task 2", project_id: 2, complete: false, priority: 4, due_at: "2013-3-12")
Task.create(name: "task 3", project_id: 2, complete: false, priority: 5, due_at: "2013-4-13")
Task.create(name: "task 7", project_id: 2, complete: false, priority: 3, due_at: "2013-4-14")
Task.create(name: "task 8", project_id: 2, complete: false, priority: 4, due_at: "2013-4-15")
Task.create(name: "task 9", project_id: 2, complete: false, priority: 5, due_at: "2013-4-16")

Task.create(name: "task 1", project_id: 3, complete: false, priority: 2, due_at: "2013-5-18")
Task.create(name: "task 2", project_id: 3, complete: false, priority: 4, due_at: "2013-5-19")
Task.create(name: "task 3", project_id: 3, complete: false, priority: 6, due_at: "2013-6-20")
Task.create(name: "task 10", project_id: 3, complete: false, priority: 8, due_at: "2013-6-21")
Task.create(name: "task 11", project_id: 3, complete: false, priority: 1, due_at: "2013-6-16")
Task.create(name: "task 12", project_id: 3, complete: false, priority: 9, due_at: "2013-6-14")

Task.create(name: "task 1", project_id: 4, complete: false, priority: 1, due_at: "2013-7-12")
Task.create(name: "task 2", project_id: 4, complete: false, priority: 3, due_at: "2013-7-19")
Task.create(name: "task 3", project_id: 4, complete: false, priority: 5, due_at: "2013-8-1")
Task.create(name: "task 13", project_id: 4, complete: false, priority: 7, due_at: "2013-8-21")
Task.create(name: "task 14", project_id: 4, complete: false, priority: 8, due_at: "2013-9-9")
Task.create(name: "task 15", project_id: 4, complete: false, priority: 9, due_at: "2013-10-30")

User.create(first_name: "Matz")
User.create(first_name: "Yehuda", last_name: "Katz")
User.create(first_name: "DHH")
User.create(first_name: "Jose", last_name: "Valim")
User.create(first_name: "Dr", last_name: "Nic")
User.create(first_name: "John", middle_initial: "A", last_name: "Nunemaker")
User.create(first_name: "Aaron", middle_initial: "B", last_name: "Patterson")
User.create(first_name: "Avdi", middle_initial: "C", last_name: "Grimm")